### ISSUE TITLE
Add Button and Display Image associated with NFT

### ISSUE THREAD

**Issue by andytudhope** [andytudhope/StatusSeekers#10]
Put in a new button that will spoof scanning a QR code meant to return an NFT rather than 1 of the 12 key words.

This will involve a call to the server (a simple Express API) that will take the tokenID found by the user sign the transaction, submit it and return to the user the new information regarding their token which we will use in another issue to render an image in the webView associated with that level (each level translates to a new "dimension" or attribute of the token.

Extra points here for some javascript the can generate procedurally a new part of the image when further attributes are added to the NFT on additional scans.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0ef318b4a88311f6472e873d6d39318495e25921d0bad2905e5f0ec4f9d3b42c](https://etherscan.io/tx/0x0ef318b4a88311f6472e873d6d39318495e25921d0bad2905e5f0ec4f9d3b42c)
