### ISSUE TITLE
Store found words in a drag n drop component

### ISSUE THREAD

**Issue by andytudhope** [andytudhope/StatusSeekers#2]
## Type
Feature Request

## Description
Currently, `call()`ing the smart contract will return randomly one of the 12 words required to unlock the Status account with a reward in it. However, it does not store them anywhere.

I would like to: 

1. implement a Redux store for this, 
2. split `App.js` into more bite-sized components and 
3. have a simple div that will display the words and allow users to drag around and re-order the words into what they think is the correct order to unlock the reward account (based on cues provided on the art work itself). 
4. They should also be able to easily copy all 12 words once found and reordered so that they can submit them to the bot to be checked.

Simple version of this might be achieved with [react-dragula](https://github.com/bevacqua/react-dragula)

A more complete version, and the one I think I am really after would likely be best achieved with [react-dnd](https://react-dnd.github.io/react-dnd/) in tandem with the [touch backend](https://github.com/yahoo/react-dnd-touch-backend).

## Requirements

1. Remove the explanatory text currently there as a placeholder.
2. Move the `Get Key Word` button to the top of the page and change it to `Scan QR Code`. This has not been implemented yet though, so keep the current logic the same for now (issue for this is [here](https://github.com/status-im/status-react/issues/2854))
3. Implement steps 1 through 4 outlined above so that each word returned after pressing the button is stored in a new div where it can be easily dragged around and re-ordered.
4. Refactoring `App.js` into separate, more modular components, and using a Redux store (or some other efficient way of passing data between components) is actually the crux of this bounty. PRs that don't do this will not even be considered.
5. Extra points for animations.

<img width="308" alt="screen shot 2017-12-30 at 1 31 24 pm" src="https://user-images.githubusercontent.com/13001517/34453817-ca6ffd2c-ed65-11e7-9805-d9d0db6f4ed4.png">

## Notes

In case you're thinking, "It would be awesome and even more intuitive if, instead of a `copy` button at the bottom there, we could just submit the words directly from the DApp to the bot", the answer is: "Yes, it totally would be. But that functionality does not yet exist and is on the list of things to do along with QR code scanning."

**Comment by status-open-bounty** [comment]
Balance: 0.300000 ETH
Contract address: [0xd655f857ffa537441674c3773898da024fd1bad3](https://etherscan.io/address/0xd655f857ffa537441674c3773898da024fd1bad3)
Network: Mainnet
Paid to: JasoonS
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by JasoonS** [comment]
@andytudhope ~~It looks like you didn't commit the `src/utils/getWeb3.js' file to repo. (As it is required in `./src/App.js` on line 4, and it cannot be found)~~ Never mind, I've worked it out, it is just from one of the truffle-boxes. 

I'll take a proper look at this tomorrow. :)

**Comment by shrugs** [comment]
Implemented in https://github.com/andytudhope/StatusSeekers/pull/3

**Comment by JasoonS** [comment]
Ah, @Shrugs beat me to it! I might as well still try merge in the Redux setup I did yesterday...

What is the point of putting a bounty on this if people from TrueBit just do the work anyway? :sweat_smile:

Anyway, happy new year!
