### ISSUE TITLE
NFT contract that adds attributes

### ISSUE THREAD

**Issue by andytudhope** [andytudhope/StatusSeekers#9]
Refactor the NFTCollectable contract to handle a slightly new direction for our NFTs. 

1. We have decided each person will only get one NFT, with 13 levels
2. This NFT will be generated based on an image the person draws
3. Scanning additional QRs will cause more levels of the NFT to be filled (bitwise shifts)

For my own reference, each new level will cause the UI to generate another part of the image procedurally.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 900.00
Contract address: [0x6d4b612be2c677d24ae92a5b91a2b97c327011d7](https://etherscan.io/address/0x6d4b612be2c677d24ae92a5b91a2b97c327011d7)
Network: Mainnet
Paid to: JasoonS
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
